# Test

# Server
server.port=0

# Environment
sis.application.environment=test

# Test Schema Strategy
spring.jpa.hibernate.ddl-auto=create-drop

# Hibernate SQL Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Logging
logging.level.root=WARN
logging.level.org.aliniazi.sis=DEBUG