# Development

# Server
server.port=8080

# Environment
sis.application.environment=development

# Logging
logging.level.root=INFO
logging.level.org.aliniazi.sis=DEBUG

# Hibernate SQL Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Database
#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=

# Development Schema Strategy
spring.jpa.hibernate.ddl-auto=update

