# Production

# Server
server.port=8080

# Environment
sis.application.environment=production


# Production Schema Strategy
spring.jpa.hibernate.ddl-auto=validate

# Database
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

# Hibernate SQL Logging
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=OFF

# Logging
logging.level.root=INFO
logging.level.org.aliniazi.sis=INFO