# Application
spring.application.name=sis
spring.application.version=0.0.1-SNAPSHOT

# Server
server.port=8080

# Profile
spring.profiles.default=dev

# Spring MVC
spring.mvc.problemdetails.enabled=true
spring.web.resources.add-mappings=false

# Banner
spring.main.banner-mode=console

# SIS Configuration
sis.application.name=${spring.application.name}
sis.application.version=${spring.application.version}
sis.application.environment=${spring.profiles.active:default}

# Logging
logging.level.root=INFO
logging.level.org.aliniazi.sis=DEBUG
logging.file.name=logs/sis.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB